# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 14:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
        migrations.AlterField(
            model_name='ride',
            name='leavedate',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True),
        ),
    ]
