# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='sex',
            field=models.CharField(max_length=10, default="Արական"),
        ),
    ]
