# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='passenger_number',
            field=models.IntegerField(default=2),
        ),
    ]
