# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='leavedate',
            field=models.DateField(blank=True),
        ),
    ]
