# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160229_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='endtime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
