# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20151219_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='endtime',
            field=models.TimeField(blank=True, default="17:55"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='leavedate',
            field=models.DateTimeField(blank=True),
        ),
    ]
