# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160306_1547'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='driver',
            name='featured_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Image'),
        ),
    ]
