# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160307_0526'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='driver',
            name='dob',
            field=models.IntegerField(default=1985),
        ),
        migrations.AddField(
            model_name='driver',
            name='mobile_prefix',
            field=models.IntegerField(default=45, max_length=3),
        ),
        migrations.AlterField(
            model_name='driver',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
