# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20151220_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='featured_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='/uploads/', verbose_name='Featured Image'),
        ),
    ]
