# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20151221_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploads/cars')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Driver')),
            ],
            options={
                'verbose_name': 'Driver Car Image',
                'verbose_name_plural': 'Driver Car Images',
            },
        ),
    ]
