# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_drivercarimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='drivercarimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/cars'),
        ),
    ]
