# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_driver_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
