# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-13 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160311_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='fromwhere',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='leavedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='towhere',
            field=models.CharField(max_length=80),
        ),
    ]
