# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20151221_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='mobile',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
    ]
