# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-14 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160313_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='uuid',
            field=models.CharField(default='000000000000000', max_length=40),
        ),
    ]
