# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_ride_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_plate', models.CharField(default='19oo199', max_length=10)),
                ('car_brand', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ab_car',
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carimgs', to='main.Car')),
            ],
            options={
                'db_table': 'ab_carimage',
                'verbose_name': 'Car Image',
                'verbose_name_plural': 'Car Images',
            },
        ),
        migrations.RemoveField(
            model_name='driverimage',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='licence_plate',
        ),
        migrations.DeleteModel(
            name='DriverImage',
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Driver'),
        ),
    ]
