# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_howitworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howitworks',
            name='desc',
            field=models.TextField(),
        ),
    ]
