# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20151222_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='howmuch',
            field=models.IntegerField(blank=True),
        ),
    ]
