# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160408_0240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='driver',
            name='mobile_prefix',
            field=models.CharField(default='055', max_length=3),
        ),
        migrations.AlterField(
            model_name='driver',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
