# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160411_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='mobile_prefix',
        ),
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='sex',
            field=models.CharField(default='\u0531\u0580\u0561\u056f\u0561\u0576', max_length=10),
        ),
        migrations.AlterField(
            model_name='ride',
            name='passenger_number',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
