# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_usersearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u0537\u056c\u2024 \u0583\u0578\u057d\u057f'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='\u0546\u0561\u0574\u0561\u056f'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u0531\u0576\u0578\u0582\u0576'),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='fromwhere',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='leavedate',
            field=models.DateField(blank=True, verbose_name='\u0544\u0565\u056f\u0576\u0574\u0561\u0576 \u0561\u0574\u057d\u0561\u0569\u056b\u057e'),
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='towhere',
            field=models.CharField(max_length=100),
        ),
    ]
