# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160419_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
