# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-06 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20160115_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HowItWorks',
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='leavedate',
            field=models.DateField(blank=True),
        ),
    ]
